---
- name: fedora initial setup
  hosts: fedora_workstation
  remote_user: root
  yum:
    name:
      - transmission
      - gnome-tweaks
      - dnf-plugins-core
      - cmatrix
      - liveusb-creator
      - numix-icon-theme-circle
      - npm
      - pygtk2
      - wireshark
      - nmap
      - unar
      - python-virtualenv
      - python3-flask
      - neofetch
      - tlp
      - ansible
    state: present
    
- name: remove unused packages
  hosts: fedora_workstation
  remote_user: root
  yum:
    name:
      - rhythmbox
      - gnome-contacts
      - gnome-maps
    state: absent

# automatically uses installed python version (pyhton3)
- name: install python pip3 package
  pip:
    name:
      - flask
      - flask-sqlalchemy
      - flask-login
      - jupyterlab
      - notebook
      - twine
    state: present 
    
- name: upgrade all yum-installed packages
  hosts: fedora_workstation
  remote_user: root
  yum:
    name: '*'
    state: latest
