---

# performs a full configuration of a cleanly installed fedora operating system

- name: enable rpm fusion repositories
  hosts: fedora_workstation
  tasks:
    - name: enable rpm fusion free repository
      command: dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y
      become: true
    - name: enable rpm fusion non-free repository
      command: dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
      become: true

- name: install papyrus icon pack
  hosts: fedora_workstation
  tasks:
    - name: enable papyrus repository
      command: dnf copr enable dirkdavidis/papirus-icon-theme -y
      become: true
    - name: update dnf cache
      command: dnf update -y
      become: true
    - name: install papyrus icons
      command: dnf install -y papirus-icon-theme
      become: true

- name: install flatpak applications
  hosts: fedora_workstation
  tasks:
    - name: Enable Flathub repository
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      become: true
    - name: application installs
      # placing the command in quotes is required if a variable is at the start of the command
      command: flatpak install --assumeyes flathub {{ flatpak }}
      become: true
        flatpak:
          - com.skype.Client
          - com.visualstudio.code
          - us.zoom.Zoom
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - com.elsevier.MendeleyDesktop
          - com.obsproject.Studio

- name: install yum applications
  hosts: fedora_workstation
  become: true
  yum:
    name:
      - transmission
      - gnome-tweaks
      - dnf-plugins-core
      - cmatrix
      - liveusb-creator
      - numix-icon-theme-circle
      - npm
      - pygtk2
      - wireshark
      - nmap
      - unar
      - python-virtualenv
      - python3-flask
      - neofetch
      - tlp
      - ansible
      - gimp
      - inkscape
      - krita
      - xournal
      - ffmpeg
      - ffmpeg-devel
    state: present

# automatically uses installed python version (pyhton3)
- name: install python pip3 package
  pip:
    name:
      - flask
      - flask-sqlalchemy
      - flask-login
      - jupyterlab
      - notebook
      - twine
    state: present 
    
- name: remove unused packages
  hosts: fedora_workstation
  become: true
  yum:
    name:
      - rhythmbox
      - gnome-contacts
      - gnome-maps
    state: absent
    
- name: upgrade all yum-installed packages
  hosts: fedora_workstation
  become: true
  yum:
    name: '*'
    state: latest
