---
- name: fedora initial setup
  hosts: fedora_workstation
  become: true
  yum:
    name:
      - transmission
      - gnome-tweaks
      - dnf-plugins-core
      - cmatrix
      - liveusb-creator
      - numix-icon-theme-circle
      - npm
      - pygtk2
      - wireshark
      - nmap
      - unar
      - python-virtualenv
      - python3-flask
      - neofetch
      - tlp
      - ansible
      - gimp
      - inkscape
      - krita
      - xournal
    state: present
    
- name: remove unused packages
  hosts: fedora_workstation
  become: true
  yum:
    name:
      - rhythmbox
      - gnome-contacts
      - gnome-maps
    state: absent

# automatically uses installed python version (pyhton3)
- name: install python pip3 package
  pip:
    name:
      - flask
      - flask-sqlalchemy
      - flask-login
      - jupyterlab
      - notebook
      - twine
    state: present 

- name: install flatpak applications
  hosts: fedora_workstation
  tasks:
    - name: Enable Flathub repository
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      become: yes
    - name: application installs
      command: flatpak install --assumeyes flathub {{ flatpak }}
      become: yes
        flatpak:
          - com.skype.Client
          - com.visualstudio.code
          - us.zoom.Zoom
          - com.valvesoftware.Steam
          - com.discordapp.Discord
          - com.elsevier.MendeleyDesktop
          - com.obsproject.Studio
    
- name: upgrade all yum-installed packages
  hosts: fedora_workstation
  become: true
  yum:
    name: '*'
    state: latest
